### ISSUE TITLE
Cleanup of builds of unsupported repos

### ISSUE THREAD

**Issue by sbidoul** [sbidoul/runboat#25]
When a build is created for a repo, and later the repo is removed from the configured supported repo, the cleanup of such builds fail with 

```
Traceback (most recent call last):
  File "/app/runboat/controller.py", line 246, in walking_dead
    await func()
  File "/app/runboat/controller.py", line 137, in deployment_watcher
    await build.cleanup()
  File "/app/runboat/models.py", line 278, in cleanup
    settings.get_build_settings(
  File "/app/runboat/settings.py", line 62, in get_build_settings
    raise RepoOrBranchNotSupported(
runboat.exceptions.RepoOrBranchNotSupported: Branch 14.0 of oca/manufacture not supported.
```

**Comment by dasunhegoda** [comment]
How can I force delete an instance?
